---
title: "Plotting"
author: "Bulun Te"
date: "2024-02-16"
output:
  pdf_document: 
    latex_engine: xelatex
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,message=FALSE, warning=FALSE}

# Load the library  
# Load data

library(tidyverse)
library(lubridate)
library(circular)
library(reshape2)
library(patchwork)
library(GGally)

# Set working directory to the project root
if (!requireNamespace("here", quietly = TRUE)) {
  install.packages("here")
}
library(here)
setwd(here())

source("EDA_func.R")

# set default language and time zone
Sys.setenv(LANGUAGE = "en")
Sys.setlocale("LC_TIME", "en_US.UTF-8")

load("GroupData.RData")

```

```{r}

plot(data_xin$Total.ST.min, type = "l", col = "blue", xlab = "Time", ylab = "Total Screen Time (min)", main = "Total Screen Time for Xinwei Wang")
plot(data_bulun$Total.ST.min, type = "l", col = "blue", xlab = "Time", ylab = "Total Screen Time (min)", main = "Total Screen Time for Bulun Te")
plot(data_zhang$Total.ST.min, type = "l", col = "blue", xlab = "Time", ylab = "Total Screen Time (min)", main = "Total Screen Time for Xinyu Zhang")

```

```{r}

plot(diff(data_xin$Total.ST.min), type = "l", col = "blue", xlab = "Time", ylab = "Total Screen Time (min)", main = "Total Screen Time for Xinwei Wang")
plot(diff(data_bulun$Total.ST.min), type = "l", col = "blue", xlab = "Time", ylab = "Total Screen Time (min)", main = "Total Screen Time for Bulun Te")
plot(diff(data_zhang$Total.ST.min), type = "l", col = "blue", xlab = "Time", ylab = "Total Screen Time (min)", main = "Total Screen Time for Xinyu Zhang")

```

```{r}

```




```{r}

acf(data_xin$Total.ST.min, lag.max = 100, main = "ACF for Total Screen Time for Xinwei Wang")
acf(data_bulun$Total.ST.min, lag.max = 100, main = "ACF for Total Screen Time for Bulun Te")
acf(data_zhang$Total.ST.min, lag.max = 100, main = "ACF for Total Screen Time for Xinyu Zhang")

```

```{r}

pacf(data_xin$Total.ST.min, lag.max = 100, main = "PACF for Total Screen Time for Xinwei Wang")
pacf(data_bulun$Total.ST.min, lag.max = 100, main = "PACF for Total Screen Time for Bulun Te")
pacf(data_zhang$Total.ST.min, lag.max = 100, main = "PACF for Total Screen Time for Xinyu Zhang")

```

```{r}

ur.ers(data_xin$Total.ST.min,
       model="trend",
       lag.max=15) %>% summary()

ur.ers(data_bulun$Total.ST.min,
       model="trend",
       lag.max=15) %>% summary()

ur.ers(data_zhang$Total.ST.min,
       model="trend",
       lag.max=15) %>% summary()

```

```{r}


```



## Circular plot for Pickup.1st

```{r,fig.width=20, fig.height=20}

png("circular_plot.png", width=20, height=20, units="in", res=500)

par(mar=c(0.1,0.1,1,15),
        mfrow=c(3,2),
    cex=1.1)

circular_plot(data_bulun,"Bulun Te")
circular_plot(data_xin,"Xinwei Wang")
circular_plot(data_zhang,"Xinyu Zhang")
dev.off()

```


## Violin plot for Social Screen Time grouped by stayup

```{r,fig.width=15, fig.height=14}

violin_bulun = violin_plot(data_bulun,"Bulun Te",trim = TRUE)

violin_xin = violin_plot(data_xin,"Xinwei Wang")

violin_zhang = violin_plot(data_zhang,"Xinyu Zhang")


occu_bulun = plot_occupation_time_curve(data_bulun, "Social.ST.min", "Semester", c(1, 0), c("blue", "red"),"Bulun Te")
occu_xin = plot_occupation_time_curve(data_xin, "Social.ST.min", "Semester", c(1, 0), c("blue", "red"),"Xinwei Wang")
occu_zhang = plot_occupation_time_curve(data_zhang, "Social.ST.min", "Semester", c(1, 0), c("blue", "red"),"Xinyu Zhang")

violin_bulun+violin_xin+violin_zhang+occu_bulun+occu_xin+occu_zhang+plot_layout(ncol = 3)



```


```{r}

cormat = cor(data_xin %>% select(Total.ST.min,
                                 Social.ST.min,
                                 Pickups,
                                 Duration.per.use,
                                 Temperature_C))
melted_cormat = melt(cormat)
ggplot(melted_cormat, aes(Var1, Var2, fill=value))+
  geom_tile(color="white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint=0, limit=c(-1,1), space="Lab", 
                       name="Pearson\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1))+
  coord_fixed()+
  labs(title = "Heatmap for Correlation Matrix for Xinwei Wang")

```


```{r,fig.width=15, fig.height=14}

# ggpairs(data_xin %>% select(Total.ST.min,
#                             Social.ST.min,
#                             Pickups,
#                             Duration.per.use,
#                             Temperature_F),
#         lower = list(continuous = wrap("points", alpha = 0.3, size = 2.5)), 
#         axisLabels = "none")+
#         theme(text = element_text(size = 25), # 调整所有文本大小
#         axis.title = element_text(size = 14), # 调整轴标题大小
#         axis.text = element_text(size = 12))+
#   labs(title = "Pairwise Scatterplot for Xinwei Wang")+
#   theme(plot.title = element_text(hjust = 0.5))

plot_pairwise(data_xin, "Xinwei Wang")
#plot_pairwise(data_bulun, "Bulun Te")
plot_pairwise(data_zhang, "Xinyu Zhang")




```



```{r,fig.width=15, fig.height=14}



plot_IMF(data_bulun, "Bulun Te")
plot_IMF(data_xin, "Xinwei Wang")
plot_IMF(data_zhang, "Xinyu Zhang")



```

```{r,fig.width=15, fig.height=14}

```






